In [40]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns

Загрузка данных
=

In [41]:
ds_original = pd.read_csv("../data/V4_classification_lr3.csv")

Работа с исходными данными
=

Описательная статистика
-

Выведем информацию о датасете, чтобы посмотреть типы данных, отсутствующие данные и в целом на доступные столбики

In [42]:
ds_original.info()

<class 'pandas.DataFrame'>
RangeIndex: 505354 entries, 0 to 505353
Data columns (total 55 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   Elevation                           505354 non-null  float64
 1   Aspect                              505354 non-null  float64
 2   Slope                               505354 non-null  float64
 3   Horizontal_Distance_To_Hydrology    505354 non-null  float64
 4   Vertical_Distance_To_Hydrology      505354 non-null  float64
 5   Horizontal_Distance_To_Roadways     505354 non-null  float64
 6   Hillshade_9am                       505354 non-null  float64
 7   Hillshade_Noon                      505354 non-null  float64
 8   Hillshade_3pm                       505354 non-null  float64
 9   Horizontal_Distance_To_Fire_Points  505354 non-null  float64
 10  Wilderness_Area_0                   505354 non-null  float64
 11  Wilderness_Area_1                   505354 non-null  float64
 12  Wilderness_Area_2                   505354 non-null  float64
 13  Wilderness_Area_3                   505354 non-null  float64
 14  Soil_Type_0                         505354 non-null  float64
 15  Soil_Type_1                         505354 non-null  float64
 16  Soil_Type_2                         505354 non-null  float64
 17  Soil_Type_3                         505354 non-null  float64
 18  Soil_Type_4                         505354 non-null  float64
 19  Soil_Type_5                         505354 non-null  float64
 20  Soil_Type_6                         505354 non-null  float64
 21  Soil_Type_7                         505354 non-null  float64
 22  Soil_Type_8                         505354 non-null  float64
 23  Soil_Type_9                         505354 non-null  float64
 24  Soil_Type_10                        505354 non-null  float64
 25  Soil_Type_11                        505354 non-null  float64
 26  Soil_Type_12                        505354 non-null  float64
 27  Soil_Type_13                        505354 non-null  float64
 28  Soil_Type_14                        505354 non-null  float64
 29  Soil_Type_15                        505354 non-null  float64
 30  Soil_Type_16                        505354 non-null  float64
 31  Soil_Type_17                        505354 non-null  float64
 32  Soil_Type_18                        505354 non-null  float64
 33  Soil_Type_19                        505354 non-null  float64
 34  Soil_Type_20                        505354 non-null  float64
 35  Soil_Type_21                        505354 non-null  float64
 36  Soil_Type_22                        505354 non-null  float64
 37  Soil_Type_23                        505354 non-null  float64
 38  Soil_Type_24                        505354 non-null  float64
 39  Soil_Type_25                        505354 non-null  float64
 40  Soil_Type_26                        505354 non-null  float64
 41  Soil_Type_27                        505354 non-null  float64
 42  Soil_Type_28                        505354 non-null  float64
 43  Soil_Type_29                        505354 non-null  float64
 44  Soil_Type_30                        505354 non-null  float64
 45  Soil_Type_31                        505354 non-null  float64
 46  Soil_Type_32                        505354 non-null  float64
 47  Soil_Type_33                        505354 non-null  float64
 48  Soil_Type_34                        505354 non-null  float64
 49  Soil_Type_35                        505354 non-null  float64
 50  Soil_Type_36                        505354 non-null  float64
 51  Soil_Type_37                        505354 non-null  float64
 52  Soil_Type_38                        505354 non-null  float64
 53  Soil_Type_39                        505354 non-null  float64
 54  Cover_Type                          505354 non-null  int64
dtypes: float64(54), int64(1)
memory usage: 212.1 MB

Теперь посмотрим на то как выглядят значения

In [43]:
ds_original.head()

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type_31,Soil_Type_32,Soil_Type_33,Soil_Type_34,Soil_Type_35,Soil_Type_36,Soil_Type_37,Soil_Type_38,Soil_Type_39,Cover_Type
0,2596.0,51.0,3.0,258.0,0.0,510.0,221.0,232.0,148.0,6279.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5
1,2590.0,56.0,2.0,212.0,-6.0,390.0,220.0,235.0,151.0,6225.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5
2,2804.0,139.0,9.0,268.0,65.0,3180.0,234.0,238.0,135.0,6121.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
3,2785.0,155.0,18.0,242.0,118.0,3090.0,238.0,238.0,122.0,6211.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
4,2595.0,45.0,2.0,153.0,-1.0,391.0,220.0,234.0,150.0,6172.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5

Тут можно видеть, что много бинарных данных(надо подумать как их визулизировать) и есть подозрение, что некоторые небинарные данные будут около уникальные и придётся их объединять их по промежуткам.

Теперь выведу статистику для числовых значений.

In [44]:
ds_original.describe()

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type_31,Soil_Type_32,Soil_Type_33,Soil_Type_34,Soil_Type_35,Soil_Type_36,Soil_Type_37,Soil_Type_38,Soil_Type_39,Cover_Type
count,505354.000000,505354.000000,505354.000000,505354.000000,505354.000000,505354.000000,505354.000000,505354.000000,505354.000000,505354.000000,...,505354.000000,505354.000000,505354.000000,505354.000000,505354.000000,505354.000000,505354.000000,505354.000000,505354.000000,505354.000000
mean,2951.588077,154.787515,13.767395,266.157094,46.002424,2431.980042,212.282707,223.256304,142.579133,2010.136114,...,0.091896,0.067076,0.001397,0.002753,0.000235,0.000590,0.026752,0.020592,0.013523,2.058935
std,275.484245,112.662899,7.473798,211.088728,57.901110,1600.415377,26.629387,19.580770,37.781550,1357.817931,...,0.288879,0.250153,0.037351,0.052392,0.015344,0.024276,0.161357,0.142012,0.115500,1.389396
min,1859.000000,0.000000,0.000000,0.000000,-159.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,2814.000000,57.000000,8.000000,108.000000,7.000000,1140.000000,199.000000,213.000000,120.000000,1024.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
50%,2987.000000,124.000000,13.000000,216.000000,29.000000,2078.000000,218.000000,226.000000,143.000000,1725.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
75%,3142.000000,263.000000,18.000000,379.000000,67.000000,3475.000000,231.000000,237.000000,168.000000,2592.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
max,3858.000000,360.000000,66.000000,1397.000000,601.000000,7117.000000,254.000000,254.000000,254.000000,7173.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,7.000000

Опытным путём было замечено, что все значения в столбиках целочисленные, значит можно заменить тип каждой колонки на int, чтобы увеличить скорость работы и увеличить читаемость

In [45]:
for column in ds_original.columns:
    ds_original[column] = ds_original[column].astype("int64")

In [ ]:
ds_original.info()

<class 'pandas.DataFrame'>
RangeIndex: 505354 entries, 0 to 505353
Data columns (total 55 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   Elevation                           505354 non-null  int64
 1   Aspect                              505354 non-null  int64
 2   Slope                               505354 non-null  int64
 3   Horizontal_Distance_To_Hydrology    505354 non-null  int64
 4   Vertical_Distance_To_Hydrology      505354 non-null  int64
 5   Horizontal_Distance_To_Roadways     505354 non-null  int64
 6   Hillshade_9am                       505354 non-null  int64
 7   Hillshade_Noon                      505354 non-null  int64
 8   Hillshade_3pm                       505354 non-null  int64
 9   Horizontal_Distance_To_Fire_Points  505354 non-null  int64
 10  Wilderness_Area_0                   505354 non-null  int64
 11  Wilderness_Area_1                   505354 non-null  int64
 12  Wilderness_Area_2                   505354 non-null  int64
 13  Wilderness_Area_3                   505354 non-null  int64
 14  Soil_Type_0                         505354 non-null  int64
 15  Soil_Type_1                         505354 non-null  int64
 16  Soil_Type_2                         505354 non-null  int64
 17  Soil_Type_3                         505354 non-null  int64
 18  Soil_Type_4                         505354 non-null  int64
 19  Soil_Type_5                         505354 non-null  int64
 20  Soil_Type_6                         505354 non-null  int64
 21  Soil_Type_7                         505354 non-null  int64
 22  Soil_Type_8                         505354 non-null  int64
 23  Soil_Type_9                         505354 non-null  int64
 24  Soil_Type_10                        505354 non-null  int64
 25  Soil_Type_11                        505354 non-null  int64
 26  Soil_Type_12                        505354 non-null  int64
 27  Soil_Type_13                        505354 non-null  int64
 28  Soil_Type_14                        505354 non-null  int64
 29  Soil_Type_15                        505354 non-null  int64
 30  Soil_Type_16                        505354 non-null  int64
 31  Soil_Type_17                        505354 non-null  int64
 32  Soil_Type_18                        505354 non-null  int64
 33  Soil_Type_19                        505354 non-null  int64
 34  Soil_Type_20                        505354 non-null  int64
 35  Soil_Type_21                        505354 non-null  int64
 36  Soil_Type_22                        505354 non-null  int64
 37  Soil_Type_23                        505354 non-null  int64
 38  Soil_Type_24                        505354 non-null  int64
 39  Soil_Type_25                        505354 non-null  int64
 40  Soil_Type_26                        505354 non-null  int64
 41  Soil_Type_27                        505354 non-null  int64
 42  Soil_Type_28                        505354 non-null  int64
 43  Soil_Type_29                        505354 non-null  int64
 44  Soil_Type_30                        505354 non-null  int64
 45  Soil_Type_31                        505354 non-null  int64
 46  Soil_Type_32                        505354 non-null  int64
 47  Soil_Type_33                        505354 non-null  int64
 48  Soil_Type_34                        505354 non-null  int64
 49  Soil_Type_35                        505354 non-null  int64
 50  Soil_Type_36                        505354 non-null  int64
 51  Soil_Type_37                        505354 non-null  int64
 52  Soil_Type_38                        505354 non-null  int64
 53  Soil_Type_39                        505354 non-null  int64
 54  Cover_Type                          505354 non-null  int64
dtypes: int64(55)
memory usage: 212.1 MB

Теперь видим, что все колонки стали int. На этом заканчивается описательная статистика датасета.

Одномерная визуализация данных
-

Начнём с построения гистограмм для каждого столбика, начну с стобика Elevation